name: Release Plugin

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install qgis-plugin-ci
        run: pip3 install qgis-plugin-ci

      - name: Deploy plugin
        env:
          TAG: ${{ github.event.release.tag_name }}
        run: |
          VERSION="${TAG#v}"
          qgis-plugin-ci release "$VERSION" \
            --release-tag "$TAG" \
            --github-token "${{ secrets.GITHUB_TOKEN }}" \
            --osgeo-username "${{ secrets.OSGEO_USER }}" \
            --osgeo-password "${{ secrets.OSGEO_PASSWORD }}"
